// grammar — the CDRCA statement grammar (v2 syntax), as a built-in plugin.
//
// ⚠️ ARCHITECTURAL DEBT — see docs/design/LANGUAGE-PLAN.md's top section.
//   v2 is the only syntax anyone should write or that any doc shows, but
//   it is NOT yet the only syntax the parser accepts: this plugin rewrites
//   v2 to legacy TEXT, and every other plugin's legacy parsing is still
//   fully intact underneath it. Hand-written legacy syntax still silently
//   compiles today. Converting this to a token-level customRule hook (so
//   legacy text is never produced, and legacy parsing can be deleted from
//   every plugin) is tracked as follow-up work, not done here.
//
// WHAT IT DOES
//   Reads the WHOLE FILE just before it is parsed (the ("before", "parse")
//   hook), finds statements written in the v2 syntax, checks them against the
//   registered vocabulary, and rewrites each one into the equivalent LEGACY
//   statement. Everything else — every legacy statement, every comment,
//   every scene marker, every `JS { }` body — is passed through untouched,
//   byte for byte. The existing parser and plugins then run exactly as they
//   always did.
//
//     @nav navbar glass sticky accent=#10b981     ->  @nav navbar.glass.sticky = #10b981
//     require quark                               ->  @requires quark
//     load quark.components                       ->  @useLib quark.components
//     import "story.cdrca"                        ->  @AddImport "story.cdrca"
//     js { ... }                                  ->  JS { ... }
//
// WHY `import` MEANS `@AddImport` AND NOT `@IMPORT`
//   Both embed another file's scenes, in the same order, with definitions
//   before uses. But a header-position `@IMPORT` only brings in the imported
//   file's OWN content: whatever THAT file imports in turn is silently
//   dropped, so a chain of three files loses the third. `@AddImport` is
//   correct at any depth, so the new keyword uses it. (Legacy `@IMPORT` is
//   left exactly as it was.)
//
// WHY A SOURCE REWRITE, NOT A PARSER CHANGE
//   * Output for equivalent input is identical to the legacy path BY
//     CONSTRUCTION, because it IS the legacy path.
//   * The core tokenizer carries no positions and merges neighbouring
//     one-letter names across whitespace (`x y` becomes `xy`), so a grammar
//     built on its tokens would misread one-letter names and could not point
//     at a column. This plugin lexes the text itself, so errors carry a real
//     line and column and one-letter names are ordinary names.
//   * Nothing in core needs to change.
//
// WHAT COUNTS AS v2 SYNTAX
//   A statement is only ever rewritten (or reported as an error) when its
//   SHAPE cannot be legacy syntax. `@id word` with nothing after it is legal
//   in both and is left alone; `@id word flag flag` has space-separated flags,
//   which no legacy statement has, so it is unambiguously v2 — and only then
//   is an unknown `word` a build error rather than a runtime console warning.
//
// Loaded in the plugin host's sandbox: no require(), no fs. Everything it
// needs is in this file; the vocabulary below is generated from the real
// component registries by tools/generate-vocabulary.js and checked for drift
// by tests/vocabulary.test.js.

"use strict";

// <generated:vocabulary>
// Generated by tools/generate-vocabulary.js from the live component registries.
// Do not edit by hand — run the generator, or its --check mode in CI.
const VOCABULARY = {
  "quark": {
    "capabilities": {
      "navbar": {
        "variants": [
          "modern",
          "glass",
          "minimal",
          "floating",
          "compact",
          "enterprise",
          "dark"
        ],
        "defaultVariant": "modern",
        "modifiers": [
          "sticky",
          "fixed",
          "centered",
          "full-width",
          "bordered",
          "elevated"
        ]
      },
      "sidebar": {
        "variants": [],
        "defaultVariant": null,
        "modifiers": [
          "edgy",
          "rounded",
          "compact",
          "closable"
        ]
      },
      "tabs": {
        "variants": [
          "modern",
          "pill",
          "minimal"
        ],
        "defaultVariant": "modern",
        "modifiers": [
          "centered",
          "full-width"
        ]
      },
      "breadcrumb": {
        "variants": [
          "modern",
          "minimal"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "pagination": {
        "variants": [
          "modern",
          "pill",
          "minimal"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "card": {
        "variants": [
          "modern",
          "elevated",
          "flat",
          "outlined",
          "glass",
          "soft"
        ],
        "defaultVariant": "modern",
        "modifiers": [
          "bordered",
          "rounded",
          "sharp",
          "compact",
          "spacious",
          "interactive"
        ]
      },
      "badge": {
        "variants": [
          "solid",
          "outlined",
          "soft"
        ],
        "defaultVariant": "solid",
        "modifiers": [
          "pill",
          "dense"
        ]
      },
      "avatar": {
        "variants": [
          "circle",
          "rounded",
          "sharp"
        ],
        "defaultVariant": "circle",
        "modifiers": [
          "bordered",
          "sm",
          "lg"
        ]
      },
      "alert": {
        "variants": [
          "info",
          "success",
          "warning",
          "danger"
        ],
        "defaultVariant": "info",
        "modifiers": [
          "dismissible",
          "bordered"
        ]
      },
      "callout": {
        "variants": [
          "modern",
          "soft",
          "editorial"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "button": {
        "variants": [
          "primary",
          "secondary",
          "outlined",
          "solid",
          "soft",
          "flat"
        ],
        "defaultVariant": "primary",
        "modifiers": [
          "pill",
          "sharp",
          "compact",
          "full-width",
          "elevated"
        ]
      },
      "input": {
        "variants": [
          "modern",
          "minimal",
          "soft"
        ],
        "defaultVariant": "modern",
        "modifiers": [
          "bordered",
          "rounded",
          "full-width"
        ]
      },
      "textarea": {
        "variants": [
          "modern",
          "soft"
        ],
        "defaultVariant": "modern",
        "modifiers": [
          "full-width"
        ]
      },
      "select": {
        "variants": [
          "modern",
          "minimal"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "checkbox": {
        "variants": [
          "modern"
        ],
        "defaultVariant": "modern",
        "modifiers": [
          "lg"
        ]
      },
      "radio": {
        "variants": [
          "modern"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "toggle": {
        "variants": [
          "modern",
          "pill"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "form": {
        "variants": [
          "modern",
          "compact",
          "spacious"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "modal": {
        "variants": [
          "modern",
          "glass",
          "minimal"
        ],
        "defaultVariant": "modern",
        "modifiers": [
          "rounded",
          "sharp"
        ]
      },
      "dropdown": {
        "variants": [
          "modern",
          "minimal"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "tooltip": {
        "variants": [
          "modern",
          "dark",
          "light"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "popover": {
        "variants": [
          "modern"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "toast": {
        "variants": [
          "modern",
          "success",
          "danger"
        ],
        "defaultVariant": "modern",
        "modifiers": [
          "dismissible"
        ]
      },
      "accordion": {
        "variants": [
          "modern",
          "bordered"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "progress": {
        "variants": [
          "modern",
          "pill",
          "flat"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      },
      "loader": {
        "variants": [
          "spin"
        ],
        "defaultVariant": "spin",
        "modifiers": []
      },
      "skeleton": {
        "variants": [
          "modern"
        ],
        "defaultVariant": "modern",
        "modifiers": []
      }
    },
    "families": [
      "structured",
      "soft",
      "bold"
    ]
  },
  "animations": {
    "capabilities": {
      "backdrop": {
        "variants": [],
        "defaultVariant": null,
        "modifiers": []
      }
    },
    "props": {
      "RotatingCube": "RotatingCubeProp",
      "BouncingSphere": "BouncingSphereProp"
    }
  }
};
// </generated:vocabulary>

// ember's vocabulary — hand-authored, not extracted from a live registry the
// way Quark's is. ember-core.js/-presets.js/-easings.js declare a small,
// fixed set of preset and easing names directly in source (registerPreset/
// registerEasing calls), not a runtime-queryable component list, so there is
// nothing for a generator to introspect. Kept in sync by hand; ember's own
// equivalence tests (tests/equivalence.test.js) fail loudly if it drifts
// from ember-presets.js / ember-easings.js.
VOCABULARY.ember = {
  capabilities: {
    fx: {
      // First word after `fx` (the preset). Kebab-case here; `presetMap`
      // below gives the camelCase runtime name where they differ.
      variants: ["bounce", "shake", "fade-in", "fade-out", "slide-up", "slide-down", "spin", "pulse"],
      defaultVariant: null,
      // Easings (ember-easings.js) plus every preset's own intensity/
      // direction modifiers (ember-presets.js). Not preset-specific here,
      // same as the legacy runtime: an unrecognised modifier for a given
      // preset is simply ignored by that preset's function, so accepting
      // the full set uniformly is exact parity, not looser validation.
      modifiers: ["linear", "smooth", "back", "elastic", "bounce", "subtle", "normal", "strong", "double"],
      presetMap: { "fade-in": "fadeIn", "fade-out": "fadeOut", "slide-up": "slideUp", "slide-down": "slideDown" },
      // Value kinds: "px" (a bare number, unit stripped) and "duration"
      // (ms/s, normalised to a millisecond number).
      options: { distance: "px", duration: "duration" }
    }
  }
};

// Plugin settings: `<plugin>.<name> = <value>` with no `@id` — a whole-app
// setting, not an element rule. Only `quark.family` exists today.
const SETTINGS = {
  "quark.family": {
    values: VOCABULARY.quark.families,
    compile: (v) => `JS { Quark.families.setRoot(${JSON.stringify(v)}); }`
  }
};

// `@<word>` statements that are not element rules. They look like
// `@id word flag` (`@requires quark ember`), so they must be excluded before
// anything else is decided.
const RESERVED_AT = ["IMPORT", "AddImport", "requires", "syntaxPlugin", "useLib"];

// Words that are wiring, not components. Owned by cdrca-reactive-state. Named
// here only so a v2-shaped use of one gets a helpful message instead of
// "unknown component".
const DOM_EVENTS = ["click", "input", "change", "submit", "keydown", "keyup", "focus", "blur"];
const WIRING_WORDS = ["bind"];

// Options every Quark component accepts. Value kinds: "color", "family".
const QUARK_OPTIONS = { accent: "color", family: "family" };

// Where every `object <name> = <Ctor>(...)` prop actually lives at runtime.
// Fixed, not generated — it's the module path itself, not registry data — but
// pinned by a test against the exact string `templates/starter.cdrca` writes
// by hand, so it can't silently drift from what the runtime really exposes.
const PROP_PATH_PREFIX = "ObjectAnimationSystem_INS.CORE_3d_PROPSsceneSYS.exampleProps.";

// Capabilities with no legacy `@id <cap>` meaning at all — `@id backdrop`
// alone must still be rewritten (to bare `background`), unlike a bare Quark
// component name, which already means the same thing in both syntaxes.
const BARE_REQUIRED_CAPS = ["backdrop"];

const ID_RE = /^[A-Za-z_][A-Za-z0-9_-]*$/;
const WORD_RE = /^[A-Za-z_][A-Za-z0-9_-]*$/;
// An id the LEGACY Quark parser can carry: it tokenizes on `-`, so a
// hyphenated id never worked there. v2 accepts any HTML id and falls back to
// an equivalent `JS { Quark.UI.mount(...) }` when the legacy form can't.
const LEGACY_ID_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

// ---------------------------------------------------------------- errors

// Edit distance, capped: only "close enough to be a typo" matters.
function distance(a, b) {
  if (Math.abs(a.length - b.length) > 3) return 99;
  const prev = [];
  for (let j = 0; j <= b.length; j++) prev[j] = j;
  for (let i = 1; i <= a.length; i++) {
    let last = prev[0];
    prev[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const tmp = prev[j];
      prev[j] = Math.min(
        prev[j] + 1,
        prev[j - 1] + 1,
        last + (a[i - 1] === b[j - 1] ? 0 : 1)
      );
      last = tmp;
    }
  }
  return prev[b.length];
}

function suggest(word, candidates) {
  const limit = word.length <= 4 ? 1 : 2;
  const scored = [];
  for (const c of candidates) {
    const d = distance(word.toLowerCase(), c.toLowerCase());
    if (d <= limit || c.toLowerCase().startsWith(word.toLowerCase()) || word.toLowerCase().startsWith(c.toLowerCase())) {
      scored.push({ c, d });
    }
  }
  scored.sort((x, y) => x.d - y.d || (x.c < y.c ? -1 : 1));
  return scored.slice(0, 3).map((s) => s.c);
}

function didYouMean(word, candidates) {
  const s = suggest(word, candidates);
  if (s.length === 0) return "";
  return " — did you mean " + s.map((x) => `'${x}'`).join(" or ") + "?";
}

// Where in the file is `offset`? (1-based line and column.)
function locate(lineStarts, offset) {
  let lo = 0;
  let hi = lineStarts.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (lineStarts[mid] <= offset) lo = mid;
    else hi = mid - 1;
  }
  return { line: lo + 1, col: offset - lineStarts[lo] + 1 };
}

class GrammarError extends Error {
  constructor(ctx, offset, length, message, hint) {
    const { line, col } = locate(ctx.lineStarts, offset);
    const start = ctx.lineStarts[line - 1];
    let end = ctx.src.indexOf("\n", start);
    if (end === -1) end = ctx.src.length;
    const lineText = ctx.src.slice(start, end).replace(/\r$/, "");
    const gutter = String(line);
    // Copy tabs so the caret lines up under the source in any terminal.
    const pad = lineText.slice(0, col - 1).replace(/[^\t]/g, " ");
    const carets = "^".repeat(Math.max(1, Math.min(length || 1, lineText.length - (col - 1) || 1)));
    super(
      `line ${line}, column ${col}: ${message}` +
        (hint ? `\n  ${hint}` : "") +
        `\n  ${gutter} | ${lineText}` +
        `\n  ${" ".repeat(gutter.length)} | ${pad}${carets}`
    );
    this.name = "CDRCAGrammarError";
    this.line = line;
    this.column = col;
    this.detail = message;
  }
}

// ---------------------------------------------------------------- lexing

// Split the file into statements. A statement ends at a newline that is not
// inside a string, a comment, or an open ( [ {. Blocks (`JS { ... }`,
// `def PROP X { ... }`) are therefore single statements, and their JavaScript
// bodies are never looked inside.
//
// Returns [{ start, end, commentAt, marker }] where [start, end) is the
// statement text without its newline, `commentAt` is the offset of a trailing
// top-level `//` comment (or -1), and `marker` is true for `!--- ... ---`
// header/scene lines.
function scanUnits(src) {
  const units = [];
  const n = src.length;
  let i = 0;
  while (i <= n) {
    const start = i;
    let j = i;
    let depth = 0;
    let commentAt = -1;
    while (j < n) {
      const c = src[j];
      if (c === "\n") {
        if (depth <= 0) break;
        j++;
        continue;
      }
      if (c === "/" && src[j + 1] === "/") {
        if (depth <= 0 && commentAt === -1) commentAt = j;
        while (j < n && src[j] !== "\n") j++;
        continue;
      }
      if (c === "/" && src[j + 1] === "*") {
        const close = src.indexOf("*/", j + 2);
        j = close === -1 ? n : close + 2;
        continue;
      }
      if (c === '"' || c === "'") {
        // Strings are single-line: an unclosed quote is just a character, so
        // one stray apostrophe can never swallow the rest of the file.
        let k = j + 1;
        while (k < n && src[k] !== c && src[k] !== "\n") {
          if (src[k] === "\\") k++;
          k++;
        }
        if (k < n && src[k] === c) {
          j = k + 1;
          continue;
        }
        j++;
        continue;
      }
      if (c === "`") {
        let k = j + 1;
        while (k < n && src[k] !== "`") {
          if (src[k] === "\\") k++;
          k++;
        }
        j = k < n ? k + 1 : n;
        continue;
      }
      if (c === "{" || c === "[" || c === "(") depth++;
      else if (c === "}" || c === "]" || c === ")") depth--;
      j++;
    }
    const text = src.slice(start, j);
    units.push({ start, end: j, commentAt, marker: /^\s*!-/.test(text) });
    if (j >= n) break;
    i = j + 1;
  }
  return units;
}

// Split on whitespace, but not inside quotes or brackets, so
// `accent=rgb(10, 20, 30)` stays one word. Offsets are into `s`.
function splitWords(s) {
  const out = [];
  const n = s.length;
  let i = 0;
  while (i < n) {
    while (i < n && /\s/.test(s[i])) i++;
    if (i >= n) break;
    const st = i;
    let depth = 0;
    while (i < n) {
      const c = s[i];
      if (c === '"' || c === "'") {
        i++;
        while (i < n && s[i] !== c) {
          if (s[i] === "\\") i++;
          i++;
        }
        i++;
        continue;
      }
      if (c === "(" || c === "[" || c === "{") depth++;
      else if (c === ")" || c === "]" || c === "}") depth--;
      else if (/\s/.test(c) && depth <= 0) break;
      i++;
    }
    out.push({ text: s.slice(st, i), start: st, end: i });
  }
  return out;
}

// ---------------------------------------------------------------- paths

// Resolve an `import "…"` path the way a web page resolves a link:
//   "bg.cdrca" / "./bg.cdrca"   next to the file that says `import`
//   "../shared/x.cdrca"         up from it
//   "/src/bg.cdrca"             from the project root
// Returns the project-root-relative path the runtime's own lookup expects.
// Returns null when the importing file's own path isn't known (a bare
// `transpile()` call with no project) — the caller then passes the text
// through unchanged, which is exactly the legacy `@IMPORT` behaviour.
function resolveImport(spec, currentFile) {
  if (typeof currentFile !== "string") return null;
  const base = spec.startsWith("/") ? [] : currentFile.split("/").slice(0, -1);
  const out = base.slice();
  for (const part of spec.split("/")) {
    if (part === "" || part === ".") continue;
    if (part === "..") {
      if (out.length === 0) return { escapes: true };
      out.pop();
    } else out.push(part);
  }
  return { path: out.join("/") };
}

// ---------------------------------------------------------------- rules

// `require`, `load`, `import`, `js` — the four directives. Returns the
// rewritten statement text, or null if this isn't one of them.
// ---------------------------------------------------------------------
// store / query / source — cdrca-reactive-state's persistence and async-data
// primitives (docs/REACTIVE-STATE.md). Today these exist ONLY as JS calls —
// `R.store(...)`, `R.query(...)`, `R.registerSource(...)` — reached through a
// `JS { }` block. These three directives compile to exactly those calls, so
// a v2 file never needs a raw JS block for them.
//
//   store <name> [persist=local|session|memory] [ttl=<ms>] = <expr>
//   source <name> = <expr>
//   query  <name> [from=<source>] [cache=<ms>] [depends=[<name>, ...]] = <expr>
//
// Options come before `=` (docs/design/LANGUAGE-PLAN.md's rule 1: a
// declaration puts its options ahead of the value it declares, since the
// grammar has no way to see where whitespace falls and so cannot tell
// `width=320px` from `width = 320px` apart by spacing — only by position).
//
// `ttl=` and `cache=` accept a bare number (milliseconds, matching the JS API
// exactly) or a suffixed duration — `500ms`, `60s`, `5m`, `2h`, `1d` — which
// is converted to milliseconds at compile time. Both compile to the same
// number; `ttl=1h` and `ttl=3600000` produce identical output.
//
// These need `cdrca-reactive-state`'s libraries staged (`load
// cdrca-reactive-state.store` / `.query`) exactly as the JS API does — this
// plugin only emits the call, same as it does for Quark.
// ---------------------------------------------------------------------

const DURATION_UNITS = { ms: 1, s: 1000, m: 60000, h: 3600000, d: 86400000 };

// A bare number of ms, or `<number><unit>`. Returns the value in ms, or
// throws with a message naming the option and what it accepts.
function durationValue(ctx, raw, at, optionName) {
  if (/^\d+$/.test(raw)) return Number(raw);
  const m = /^(\d+(?:\.\d+)?)(ms|s|m|h|d)$/.exec(raw);
  if (m) return Number(m[1]) * DURATION_UNITS[m[2]];
  throw new GrammarError(
    ctx,
    at,
    raw.length,
    `'${raw}' is not a duration`,
    `${optionName}= takes a number of milliseconds (${optionName}=3600000) or a duration (${optionName}=1h) — units: ms, s, m, h, d`
  );
}

// A comma-separated `[a, b, c]` list of bare names, as `depends=` takes.
function nameListValue(ctx, raw, at, optionName) {
  const m = /^\[([\s\S]*)\]$/.exec(raw);
  if (!m) {
    throw new GrammarError(ctx, at, raw.length, `'${raw}' is not a list`, `${optionName}= takes a bracketed list of names, e.g. ${optionName}=[a, b]`);
  }
  const inner = m[1].trim();
  if (inner === "") return [];
  const names = inner.split(",").map((s) => s.trim());
  for (const n of names) {
    if (!ID_RE.test(n)) {
      throw new GrammarError(ctx, at, raw.length, `'${n}' in ${optionName}=[...] is not a name`, "list entries are bare names, not quoted strings or expressions");
    }
  }
  return names;
}

const PERSIST_VALUES = ["local", "session", "memory"];

// `store <name> [persist=...] [ttl=...] = <expr>`
function parseStore(ctx, textStart, rest, restStart) {
  const words = splitWords(rest);
  if (words.length === 0 || !ID_RE.test(words[0].text)) {
    throw new GrammarError(ctx, textStart, "store".length, "expected a name after 'store'", "e.g. store cart = []");
  }
  const name = words[0].text;
  let i = 1;
  let persist = null;
  let ttl = null;
  while (i < words.length) {
    const w = words[i];
    const at = restStart + w.start;
    const m = /^([A-Za-z_][A-Za-z0-9_-]*)=([\s\S]*)$/.exec(w.text);
    if (!m) break;
    const [, key, value] = m;
    if (key === "persist") {
      if (PERSIST_VALUES.indexOf(value) === -1) {
        throw new GrammarError(ctx, at + key.length + 1, value.length, `unknown persist value '${value}'`, `persist is one of: ${PERSIST_VALUES.join(", ")}`);
      }
      persist = value;
    } else if (key === "ttl") {
      ttl = durationValue(ctx, value, at + key.length + 1, "ttl");
    } else {
      throw new GrammarError(ctx, at, key.length, `unknown option '${key}' for store${didYouMean(key, ["persist", "ttl"])}`, "options for store: persist, ttl");
    }
    i++;
  }
  if (!(words[i] && words[i].text === "=")) {
    throw new GrammarError(ctx, restStart + (words[i] ? words[i].start : rest.length), 1, `expected '=' after 'store ${name}'`, `e.g. store ${name} = []`);
  }
  const exprAt = restStart + (words[i + 1] ? words[i + 1].start : rest.length);
  const expr = rest.slice((words[i + 1] ? words[i + 1].start : rest.length)).trim();
  if (expr === "") {
    throw new GrammarError(ctx, exprAt, 1, `expected an initial value after 'store ${name} ='`, `e.g. store ${name} = []`);
  }
  const opts = [];
  if (persist) opts.push(`persist: ${JSON.stringify(persist)}`);
  if (ttl !== null) opts.push(`ttl: ${ttl}`);
  const optsArg = opts.length ? `, { ${opts.join(", ")} }` : "";
  // R.store() calls R.define(name, ...) itself — it is the declaration, not
  // an expression to declare something else FROM. Wrapping it in
  // `state name = R.store(...)` would try to define the same cell twice
  // (runtime.js's define() throws on a redeclaration) and would also throw
  // away store()'s real return value (the loaded-or-initial value) in favor
  // of R.set()'s. So this compiles the same way `source` does: a plain
  // side-effecting call, exactly matching hand-written
  // `JS { const R = CDRCA.reactive; R.store(...); }`.
  return `JS { const R = CDRCA.reactive; R.store(${JSON.stringify(name)}, ${expr}${optsArg}); }`;
}

// `source <name> = <expr>`
function parseSource(ctx, textStart, rest, restStart) {
  const words = splitWords(rest);
  if (words.length === 0 || !ID_RE.test(words[0].text)) {
    throw new GrammarError(ctx, textStart, "source".length, "expected a name after 'source'", 'e.g. source main = firebase({ apiKey: "..." })');
  }
  const name = words[0].text;
  if (!(words[1] && words[1].text === "=")) {
    throw new GrammarError(ctx, restStart + (words[1] ? words[1].start : rest.length), 1, `expected '=' after 'source ${name}'`);
  }
  const exprAt = restStart + (words[2] ? words[2].start : rest.length);
  const expr = rest.slice(words[2] ? words[2].start : rest.length).trim();
  if (expr === "") {
    throw new GrammarError(ctx, exprAt, 1, `expected an adapter after 'source ${name} ='`, `e.g. source ${name} = firebase({ ... })`);
  }
  return `JS { const R = CDRCA.reactive; R.registerSource(${JSON.stringify(name)}, ${expr}); }`;
}

// `query <name> [from=...] [cache=...] [depends=[...]] = <expr>`
function parseQuery(ctx, textStart, rest, restStart) {
  const words = splitWords(rest);
  if (words.length === 0 || !ID_RE.test(words[0].text)) {
    throw new GrammarError(ctx, textStart, "query".length, "expected a name after 'query'", 'e.g. query users = fetch("/api/users").then(r => r.json())');
  }
  const name = words[0].text;
  let i = 1;
  let from = null;
  let cache = null;
  let depends = null;
  while (i < words.length) {
    const w = words[i];
    const at = restStart + w.start;
    const m = /^([A-Za-z_][A-Za-z0-9_-]*)=([\s\S]*)$/.exec(w.text);
    if (!m) break;
    const [, key, value] = m;
    if (key === "from") {
      if (!ID_RE.test(value)) {
        throw new GrammarError(ctx, at + key.length + 1, value.length, `'${value}' is not a source name`, "from= takes the bare name a source was registered under, e.g. from=main");
      }
      from = value;
    } else if (key === "cache") {
      cache = durationValue(ctx, value, at + key.length + 1, "cache");
    } else if (key === "depends") {
      depends = nameListValue(ctx, value, at + key.length + 1, "depends");
    } else {
      throw new GrammarError(ctx, at, key.length, `unknown option '${key}' for query${didYouMean(key, ["from", "cache", "depends"])}`, "options for query: from, cache, depends");
    }
    i++;
  }
  if (!(words[i] && words[i].text === "=")) {
    throw new GrammarError(ctx, restStart + (words[i] ? words[i].start : rest.length), 1, `expected '=' after 'query ${name}'`, `e.g. query ${name} = fetch("/api/${name}").then(r => r.json())`);
  }
  const exprAt = restStart + (words[i + 1] ? words[i + 1].start : rest.length);
  const expr = rest.slice(words[i + 1] ? words[i + 1].start : rest.length).trim();
  if (expr === "") {
    throw new GrammarError(ctx, exprAt, 1, `expected a fetcher after 'query ${name} ='`, `e.g. query ${name} = fetch("/api/${name}").then(r => r.json())`);
  }
  const optsArg = buildQueryOpts(cache, depends);
  // Like `store`, R.query() calls R.define(name, ...) itself (the cell holds
  // { data, loading, error }, updated in place as the fetch progresses) and
  // its return value is the fetch's own Promise, meant for `await`, not a
  // value to declare a cell FROM. So this is a side-effecting call, same
  // shape as `store` and `source` — never `state name = R.query(...)`,
  // which would both double-define the cell and discard the Promise.
  if (from !== null) {
    // `from=` names a registered source (R.registerSource). The JS API's
    // matching shorthand is R.query(name, { source, ...config }) — the
    // fetcher is then a plain config object the source's get(config)
    // receives, not a function. So after `from=`, `=` takes an object
    // literal (the source-specific config), not an expression.
    if (!/^\{[\s\S]*\}$/.test(expr)) {
      throw new GrammarError(
        ctx,
        exprAt,
        expr.length,
        `'query ${name} from=${from}' needs an object after '=', e.g. query ${name} from=${from} = { url: "/api/${name}" }`,
        "without from=, '=' takes a fetcher expression instead, e.g. query users = fetch(...).then(r => r.json())"
      );
    }
    const fetcherArg = `Object.assign({ source: ${JSON.stringify(from)} }, ${expr})`;
    return `JS { const R = CDRCA.reactive; R.query(${JSON.stringify(name)}, ${fetcherArg}${optsArg}); }`;
  }
  // Without from=, R.query()'s second argument must be a FUNCTION it calls
  // each time it (re)fetches (resolveFetcher() in reactive-state-query.js
  // checks `typeof === "function"` and otherwise treats the value as a
  // plain config object — so an un-wrapped `fetch(...)` call is evaluated
  // ONCE at declaration time and its Promise is silently misread as
  // configuration, not fetched again on refetch/dependsOn). Wrapping in
  // `() => (...)` is exactly what hand-written reactive-state code already
  // does (see this plugin's own docs and README examples).
  return `JS { const R = CDRCA.reactive; R.query(${JSON.stringify(name)}, () => (${expr})${optsArg}); }`;
}

function buildQueryOpts(cache, depends) {
  const opts = [];
  if (cache !== null) opts.push(`cacheTime: ${cache}`);
  if (depends !== null) opts.push(`dependsOn: ${JSON.stringify(depends)}`);
  return opts.length ? `, { ${opts.join(", ")} }` : "";
}

function directive(ctx, unit, text, textStart) {
  const currentFile = ctx.currentFile;
  const m = /^(require|load|import|js|store|source|query)(?=\s|\{|$)/.exec(text);
  if (!m) return null;
  const kw = m[1];
  const rest = text.slice(kw.length);
  const restStart = textStart + kw.length;

  if (kw === "store" || kw === "source" || kw === "query") {
    const trimmedRest = rest.replace(/^\s+/, "");
    const trimmedStart = restStart + (rest.length - trimmedRest.length);
    if (trimmedRest === "") {
      throw new GrammarError(ctx, textStart, kw.length, `expected a name after '${kw}'`);
    }
    if (kw === "store") return parseStore(ctx, textStart, trimmedRest, trimmedStart);
    if (kw === "source") return parseSource(ctx, textStart, trimmedRest, trimmedStart);
    return parseQuery(ctx, textStart, trimmedRest, trimmedStart);
  }

  if (kw === "js") {
    // Only a block: `js { ... }`. Anything else starting with the word "js"
    // is somebody's own text, not ours.
    if (!/^\s*\{/.test(rest)) return null;
    return "JS" + rest;
  }

  if (kw === "require") {
    const names = rest.split(",").map((x) => x.trim());
    if (rest.trim() === "" || names.some((n) => n === "")) {
      throw new GrammarError(ctx, textStart, kw.length, "'require' needs at least one plugin name", "e.g. require quark, ember");
    }
    for (const nm of names) {
      if (!WORD_RE.test(nm)) {
        const at = restStart + rest.indexOf(nm);
        throw new GrammarError(ctx, at, nm.length, `'${nm}' is not a plugin name`, "plugin names are words like: require quark, ember");
      }
    }
    return "@requires " + names.join(", ");
  }

  if (kw === "load") {
    const arg = rest.trim();
    const shape = /^([A-Za-z_][A-Za-z0-9_-]*)\.([A-Za-z_][A-Za-z0-9_-]*)$/.exec(arg);
    if (!shape) {
      throw new GrammarError(
        ctx,
        textStart,
        text.length,
        arg === "" ? "'load' needs a library, written <plugin>.<library>" : `'${arg}' is not a <plugin>.<library> name`,
        "e.g. load quark.components"
      );
    }
    return "@useLib " + arg;
  }

  // import
  const arg = rest.trim();
  if (!/^"[^"\n]+"$|^'[^'\n]+'$/.test(arg)) {
    throw new GrammarError(ctx, textStart, text.length, "'import' needs a quoted file path", 'e.g. import "story.cdrca"');
  }
  const spec = arg.slice(1, -1);
  const resolved = resolveImport(spec, currentFile);
  if (resolved === null) return "@AddImport " + arg;
  const specAt = textStart + text.indexOf(arg, kw.length);
  if (resolved.escapes) {
    throw new GrammarError(ctx, specAt, arg.length, `'${spec}' goes above the project folder`, "an import has to stay inside the project");
  }
  return `@AddImport "${resolved.path}"`;
}

// Normalise a colour to what the legacy Quark value slot takes.
function colorValue(ctx, raw, at) {
  let v = raw;
  if (/^(["']).*\1$/.test(v)) v = v.slice(1, -1);
  if (/^0x[0-9a-fA-F]{6}$/.test(v)) return "#" + v.slice(2); // legacy 0xRRGGBB
  if (/^#([0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/.test(v)) return v;
  if (/^(rgb|rgba|hsl|hsla|hwb|lab|lch|oklab|oklch|color)\([^()]*\)$/i.test(v)) return v;
  if (/^[A-Za-z]+$/.test(v)) return v; // named colour
  throw new GrammarError(
    ctx,
    at,
    raw.length,
    `'${raw}' is not a colour`,
    "use #rrggbb, rgb(...), or a colour name — e.g. accent=#10b981"
  );
}

// `@id capability [flags…] [option=value…]`. Returns rewritten text, or null
// if the statement isn't v2-shaped.
function elementRule(ctx, unit, text, textStart) {
  const m = /^@([A-Za-z_][A-Za-z0-9_-]*)\s+(\S+)(?:\s+([\s\S]*))?$/.exec(text);
  if (!m) return null;
  const id = m[1];
  const capWord = m[2];
  const rest = (m[3] || "").trim();

  if (RESERVED_AT.indexOf(id) !== -1) return null;
  // `@id word` alone is the same in legacy for a Quark component (a bare
  // mount) — leave it. It is NOT the same for a capability with no legacy
  // `@id` form at all (`backdrop` — the whole thing IS the rewrite target,
  // since legacy expresses it as a bare statement, `background`, not an
  // element rule), so those must still be processed with an empty `rest`.
  const capBareName = capWord.indexOf(".") !== -1 ? capWord.slice(capWord.lastIndexOf(".") + 1) : capWord;
  if (rest === "" && BARE_REQUIRED_CAPS.indexOf(capBareName) === -1) return null;
  // Legacy shapes after the word: `= value`, `=> action`, `{ block }`.
  if (/^[=.{]/.test(rest)) return null;
  // A dotted word is legacy (`card.elevated`) unless it is `plugin.capability`.
  let plugin = null;
  let cap = capWord;
  if (capWord.indexOf(".") !== -1) {
    const [left, right, ...more] = capWord.split(".");
    if (more.length === 0 && ctx.vocab[left] && ctx.vocab[left].capabilities[right]) {
      plugin = left;
      cap = right;
    } else {
      return null;
    }
  }
  if (!WORD_RE.test(cap)) return null;

  const idAt = textStart + 1;
  const capAt = textStart + text.indexOf(capWord, 1 + id.length);
  const restAt = textStart + (text.length - (m[3] ? m[3].length : 0)) + ((m[3] || "").length - (m[3] || "").trimStart().length);

  // ---- which component? An unqualified name (no `plugin.` prefix) is
  // looked up across every plugin's vocabulary — not just Quark's, now that
  // animations and ember have one too — and it's a build error, not a
  // silent pick, if more than one plugin claims the same bare word
  // (section 3: "installing a library can therefore never change what an
  // existing file means").
  let pluginName = plugin;
  if (!pluginName) {
    const owners = Object.keys(ctx.vocab).filter((p) => ctx.vocab[p].capabilities && ctx.vocab[p].capabilities[cap]);
    if (owners.length > 1) {
      throw new GrammarError(
        ctx,
        capAt,
        cap.length,
        `'${cap}' is ambiguous — it's a component in both ${owners.join(" and ")}`,
        `qualify it: ${owners.map((p) => `@${id} ${p}.${cap}`).join("  or  ")}`
      );
    }
    pluginName = owners[0] || "quark";
  }
  const vocab = ctx.vocab[pluginName];
  const def = vocab && vocab.capabilities[cap];
  if (!def) {
    if (DOM_EVENTS.indexOf(cap) !== -1) {
      throw new GrammarError(ctx, capAt, cap.length, `'${cap}' is an event, not a component`, `to run something when it happens, write:  @${id} ${cap} => action`);
    }
    if (WIRING_WORDS.indexOf(cap) !== -1) {
      throw new GrammarError(ctx, capAt, cap.length, `'${cap}' is written with a dot and a value, not flags`, `e.g.  @${id} bind.text = someState`);
    }
    const all = [];
    for (const p of Object.keys(ctx.vocab)) {
      if (ctx.vocab[p].capabilities) all.push(...Object.keys(ctx.vocab[p].capabilities));
    }
    throw new GrammarError(
      ctx,
      capAt,
      cap.length,
      `unknown component '${cap}'${didYouMean(cap, Array.from(new Set(all)))}`,
      all.length ? "if it belongs to another plugin, add `require <plugin>` first" : ""
    );
  }

  // A capability declared by a plugin (see registry.declare) is claimed by
  // that plugin's own registered element rule, not by the generic Quark-style
  // path below — return null so the rules after this one get their turn.
  if (def.__owner) return null;

  // `@page` is reserved for `backdrop` (the whole page, no element). Using it
  // with anything else would silently try to mount into a real element with
  // id="page", which is exactly the confusion decision 1 (section 12) rules
  // out.
  if (id === "page" && !(pluginName === "animations" && cap === "backdrop")) {
    throw new GrammarError(
      ctx,
      idAt,
      "page".length,
      "'@page' is reserved for 'backdrop' (the whole page)",
      `for an element, give it a real id — e.g.  @hero ${cap} ...`
    );
  }

  if (pluginName === "animations") {
    return animationsCapabilityRule(ctx, id, cap, rest, restAt);
  }

  // ember's `fx` has its own shape entirely (no accent/family, a
  // preset-is-always-first rule, a bare trailing duration) — hand off
  // rather than forcing it through Quark's variant/modifier/accent model.
  if (pluginName === "ember") {
    return emberFxRule(ctx, id, idAt, rest, restAt, def);
  }

  // ---- flags and options
  const words = splitWords(rest);
  const variants = def.variants;
  const modifiers = def.modifiers;
  const options = QUARK_OPTIONS;
  const optionNames = Object.keys(options);
  const flagNames = variants.concat(modifiers);

  let variant = null;
  const mods = [];
  const opt = {};

  for (let w = 0; w < words.length; w++) {
    const word = words[w];
    const at = restAt + word.start;
    const t = word.text;

    const optMatch = /^([A-Za-z_][A-Za-z0-9_-]*)=([\s\S]*)$/.exec(t);
    if (optMatch) {
      const name = optMatch[1];
      const value = optMatch[2];
      if (!options[name]) {
        throw new GrammarError(ctx, at, name.length, `unknown option '${name}' for ${cap}${didYouMean(name, optionNames)}`, `options for ${cap}: ${optionNames.join(", ")}`);
      }
      if (value === "") {
        throw new GrammarError(ctx, at, t.length, `expected a value after '${name}='`, `e.g. ${name}=${options[name] === "family" ? "soft" : "#10b981"}`);
      }
      if (opt[name] !== undefined) {
        throw new GrammarError(ctx, at, t.length, `'${name}' is given twice`);
      }
      const valueAt = at + name.length + 1;
      if (options[name] === "family") {
        const fam = value.replace(/^(["'])(.*)\1$/, "$2");
        if (vocab.families.indexOf(fam) === -1) {
          throw new GrammarError(ctx, valueAt, value.length, `unknown family '${fam}'${didYouMean(fam, vocab.families)}`, `families: ${vocab.families.join(", ")}`);
        }
        opt[name] = "family:" + fam;
      } else {
        opt[name] = colorValue(ctx, value, valueAt);
      }
      continue;
    }

    if (/^["']/.test(t)) {
      throw new GrammarError(ctx, at, t.length, `${cap} doesn't take a text value here`, `flags are plain words, e.g.  @${id} ${cap} ${flagNames[0] || "..."}`);
    }

    if (!WORD_RE.test(t)) {
      throw new GrammarError(ctx, at, t.length, `unexpected '${t}'`, "flags are plain words like: glass sticky full-width");
    }

    // `accent = red` (spaced) — the most likely way to get an option wrong.
    if (optionNames.indexOf(t) !== -1 && words[w + 1] && words[w + 1].text.charAt(0) === "=") {
      throw new GrammarError(ctx, at, t.length, `write options without spaces: ${t}=value`, `e.g.  ${t}=${options[t] === "family" ? "soft" : "#10b981"}`);
    }

    if (variants.indexOf(t) !== -1) {
      if (variant !== null) {
        throw new GrammarError(ctx, at, t.length, `${cap} has one variant, and you gave two: '${variant}' and '${t}'`, `variants: ${variants.join(", ")}`);
      }
      variant = t;
    } else if (modifiers.indexOf(t) !== -1) {
      if (mods.indexOf(t) !== -1) {
        throw new GrammarError(ctx, at, t.length, `'${t}' is given twice`);
      }
      mods.push(t);
    } else {
      const parts = [];
      if (variants.length) parts.push(`variants: ${variants.join(", ")}`);
      if (modifiers.length) parts.push(`modifiers: ${modifiers.join(", ")}`);
      throw new GrammarError(ctx, at, t.length, `unknown flag '${t}' for ${cap}${didYouMean(t, flagNames)}`, parts.join("  |  ") || `${cap} takes no flags`);
    }
  }

  if (opt.accent !== undefined && opt.family !== undefined) {
    throw new GrammarError(
      ctx,
      restAt,
      rest.length,
      "accent= and family= can't be combined in one statement yet",
      "give the element one of them, and set the other for the whole app with the quark family setting"
    );
  }
  const value = opt.accent !== undefined ? opt.accent : opt.family;

  // ---- emit. Canonical order: variant first, then modifiers as written. The
  // legacy dotted form takes the FIRST word as the variant only if it is a
  // declared variant, so writing `button.pill.soft` there silently ignores
  // `soft`; putting the variant first here makes flag order not matter.
  const chain = (variant ? [variant] : []).concat(mods);

  if (LEGACY_ID_RE.test(id) && chain.every((w) => LEGACY_ID_RE.test(w))) {
    return `@${id} ${cap}` + chain.map((x) => "." + x).join("") + (value !== undefined ? " = " + value : "");
  }
  // Hyphenated ids never worked in the legacy Quark parser (it splits on `-`),
  // and a hyphenated modifier only just does. Rather than depend on either,
  // emit the exact call the legacy path would have produced, as an embedded
  // JS block that never goes through the tokenizer at all.
  const args = [JSON.stringify(id), JSON.stringify(cap), JSON.stringify(chain)];
  if (value !== undefined) args.push(JSON.stringify(value));
  return `JS { Quark.UI.mount(${args.join(", ")}); }`;
}

// `backdrop [<targetId>] [from "<file>.cdrca"]` — the ONE bare-required
// animations capability. Dispatched from elementRule() when the capability
// lookup finds `animations` (or plugin-qualified `animations.backdrop`).
function animationsCapabilityRule(ctx, id, cap, rest, restAt) {
  // Only capability animations registers today; kept as a switch so adding
  // the next one doesn't require re-deriving this dispatch.
  if (cap !== "backdrop") return null;

  const target = id === "page" ? "" : " " + id;
  if (rest === "") return "background" + target;

  const words = splitWords(rest);
  if (words.length > 1) {
    const extra = words[1];
    throw new GrammarError(
      ctx,
      restAt + extra.start,
      extra.text.length,
      `unexpected '${extra.text}' after the backdrop file`,
      `e.g.  @${id} backdrop "hero-bg.cdrca"`
    );
  }
  const w = words[0];
  if (!/^"[^"\n]*"$/.test(w.text) && !/^'[^'\n]*'$/.test(w.text)) {
    throw new GrammarError(
      ctx,
      restAt + w.start,
      w.text.length,
      `backdrop takes a quoted .cdrca file path, not '${w.text}'`,
      `e.g.  @${id} backdrop "hero-bg.cdrca"`
    );
  }
  return "background" + target + " from " + w.text;
}

// Normalise a CSS-style colour (`#rrggbb`/`#rgb`, legacy `0xrrggbb`
// passthrough) to the numeric hex literal `scene.background`'s legacy target
// (`BGcolor`) actually takes.
function sceneColorValue(ctx, raw, at) {
  if (/^0x[0-9a-fA-F]{6}$/.test(raw)) return raw;
  const m = /^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.exec(raw);
  if (!m) {
    throw new GrammarError(ctx, at, raw.length, `'${raw}' is not a colour scene.background accepts`, "use #rrggbb or #rgb — e.g.  scene.background = #1a1a2e");
  }
  let hex = m[1];
  if (hex.length === 3) hex = hex.split("").map((c) => c + c).join("");
  return "0x" + hex;
}

// `object`, `prop`, `action`, `scene.background`/`scene.gradient` — section
// 4.3's remaining v2 forms. Bare keywords, not `@id`-prefixed, so they're
// tried as a fallback after the `require`/`load`/`import`/`js` directives
// (none of these four words collide with a legacy statement's first word).
function animationsDeclaration(ctx, unit, text, textStart) {
  const sceneM = /^scene\.(background|gradient)\s*=\s*([\s\S]*)$/.exec(text);
  if (sceneM) {
    const prop = sceneM[1];
    const raw = sceneM[2];
    const valueAt = textStart + text.length - raw.length;
    if (raw.trim() === "") {
      throw new GrammarError(
        ctx,
        textStart,
        text.length,
        `expected a value after 'scene.${prop} ='`,
        prop === "background" ? "e.g.  scene.background = #1a1a2e" : 'e.g.  scene.gradient = { data: [...], width: 3 }'
      );
    }
    if (prop === "background") {
      return `BGcolor = ${sceneColorValue(ctx, raw.trim(), valueAt)}`;
    }
    return `gredientMap = ${raw}`;
  }

  const objM = /^object\s+([A-Za-z_$][\w$]*)\s*=\s*([\s\S]*)$/.exec(text);
  if (objM) {
    const name = objM[1];
    const rhs = objM[2].trim();
    const callM = /^([A-Za-z_$][\w$]*)\s*\(([\s\S]*)\)$/.exec(rhs);
    if (!callM) {
      throw new GrammarError(ctx, textStart, text.length, `expected '<Prop>(...)' after 'object ${name} ='`, `e.g.  object ${name} = BouncingSphere()`);
    }
    const ctorName = callM[1];
    const table = ctx.vocab.animations.props;
    const full = table[ctorName];
    if (!full) {
      const names = Object.keys(table);
      const at = textStart + text.indexOf(ctorName, text.indexOf("="));
      throw new GrammarError(ctx, at, ctorName.length, `unknown prop '${ctorName}'${didYouMean(ctorName, names)}`, names.length ? `known props: ${names.join(", ")}` : "");
    }
    // Every built-in prop constructor (RotatingCubeProp, BouncingSphereProp)
    // takes its color as a raw JS numeric literal (`0xRRGGBB`), the same
    // convention `scene.background`/`colorValue()` normalize TO internally
    // for everything else — but unlike those, a prop's constructor args are
    // passed straight through here with no rewriting at all, so the CSS-
    // style `#rrggbb` this language's docs actually tell authors to write
    // (docs/SYNTAX.md: `RotatingCube(#3b82f6, 1)`) compiled to literal,
    // invalid JS (`#3 b82f6`) — the tokenizer splits `#` from the hex
    // digits, and a bare `#` is not valid JS on its own. Convert each
    // standalone `#hex` argument to the `0xhex` the constructor actually
    // expects; a `#` that appears inside a quoted string argument (an
    // unlikely but possible second argument) is left untouched.
    const argsWithColorsConverted = callM[2].replace(
      /(['"`])(?:\\.|(?!\1).)*\1|#([0-9a-fA-F]{3,8})\b/g,
      (whole, _quote, hex) => (hex ? "0x" + hex : whole)
    );
    return `use ${PROP_PATH_PREFIX}${full}(${argsWithColorsConverted}) as ${name}`;
  }

  const propM = /^prop\s+([A-Za-z_$][\w$]*)([\s\S]*)$/.exec(text);
  if (propM) {
    const name = propM[1];
    let rest = propM[2];
    let abstractsClause = "";
    const abM = /^\s*abstracts=([A-Za-z_$][\w$.]*)/.exec(rest);
    if (abM) {
      abstractsClause = " abstracts " + abM[1];
      rest = rest.slice(abM[0].length);
    }
    if (!/^\s*\{[\s\S]*\}\s*$/.test(rest)) {
      throw new GrammarError(ctx, textStart, text.length, `expected a '{ ... }' body after 'prop ${name}'`, `e.g.  prop ${name} { /* js */ }`);
    }
    return `def PROP ${name}${abstractsClause} ${rest.trim()}`;
  }

  const actM = /^action\s+([A-Za-z_$][\w$]*)([\s\S]*)$/.exec(text);
  if (actM) {
    const name = actM[1];
    let rest = actM[2];
    const opts = {};
    const optRe = /^\s*(stay|lerp)=(\d+(?:\.\d+)?)(ms|s)/;
    let om;
    while ((om = optRe.exec(rest))) {
      opts[om[1]] = om[3] === "s" ? Math.round(parseFloat(om[2]) * 1000) : parseInt(om[2], 10);
      rest = rest.slice(om[0].length);
    }
    if (opts.stay === undefined || opts.lerp === undefined) {
      throw new GrammarError(ctx, textStart, text.length, `'action ${name}' needs both stay= and lerp=`, `e.g.  action ${name} stay=2000ms lerp=500ms { ... }`);
    }
    const bodyM = /^\s*\{([\s\S]*)\}\s*$/.exec(rest);
    if (!bodyM) {
      throw new GrammarError(ctx, textStart, text.length, `expected a '{ ... }' body after 'action ${name} ...'`, `e.g.  action ${name} stay=2000ms lerp=500ms { cube.modifyMesh("") }`);
    }
    const stmts = bodyM[1].split(/[;\n]+/).map((s) => s.trim()).filter((s) => s !== "");
    if (stmts.length === 0) {
      throw new GrammarError(ctx, textStart, text.length, `'action ${name}' has an empty body`, `e.g.  { cube.modifyMesh("") }`);
    }
    const parts = [];
    for (const s of stmts) {
      const cm = /^([A-Za-z_$][\w$]*(?:\.[A-Za-z_$][\w$]*)*)\.([A-Za-z_$][\w$]*)\(([\s\S]*)\)$/.exec(s);
      if (!cm) {
        throw new GrammarError(ctx, textStart, text.length, `'${s}' isn't '<object>.<method>(...)'`, `e.g.  cube.modifyMesh("")`);
      }
      parts.push(`${cm[1]} ${cm[2]} ${cm[3]}`);
    }
    return `add new action ${name} ${opts.stay} ${opts.lerp}\ndef ACTION ${name} ${parts.join(" ")}`;
  }

  return null;
}

// A bare pixel amount: `40px`. Returns the unitless number ember's presets
// expect (they take a plain px number, not a CSS string).
function pxValue(ctx, raw, at) {
  const m = /^(\d+(?:\.\d+)?)px$/.exec(raw);
  if (!m) {
    throw new GrammarError(ctx, at, raw.length, `'${raw}' is not a pixel amount`, "use a number with px — e.g. 40px");
  }
  return parseFloat(m[1]);
}

// A duration: `600ms` or `2s`, for ember and campfire — normalised to a
// millisecond number, since both runtimes take plain milliseconds. Distinct
// from this file's own `durationValue` (store/query's ms-or-unit-suffixed
// form, which also accepts m/h/d and a bare number of ms): ember/campfire
// never take a bare number, and never take m/h/d, so the two are kept
// separate rather than merged into one that's looser than either caller
// wants.
function emberDurationValue(ctx, raw, at) {
  const m = /^(\d+(?:\.\d+)?)(ms|s)$/.exec(raw);
  if (!m) {
    throw new GrammarError(ctx, at, raw.length, `'${raw}' is not a duration`, "use a number with ms or s — e.g. 600ms or 2s");
  }
  return Math.round(parseFloat(m[1]) * (m[2] === "s" ? 1000 : 1));
}

// `@id fx <preset> [modifier…] [distance=<px>] [duration=<ms|s>] [<bare duration>]`.
// ember's shape doesn't fit the Quark flags-then-accent/family model: the
// first word is ALWAYS the preset (never reachable later — see the "bounce"
// note below), and a value can also arrive as a bare trailing literal
// (`fx title shake strong 400ms`) instead of only `duration=…`.
function emberFxRule(ctx, id, idAt, rest, restAt, def) {
  const words = splitWords(rest);
  const presetNames = def.variants;
  const modifierNames = def.modifiers;
  const optionNames = Object.keys(def.options);
  let preset = null;
  const mods = [];
  const opt = {};

  for (let w = 0; w < words.length; w++) {
    const word = words[w];
    const at = restAt + word.start;
    const t = word.text;

    const optMatch = /^([A-Za-z_][A-Za-z0-9_-]*)=([\s\S]*)$/.exec(t);
    if (optMatch) {
      const name = optMatch[1];
      const value = optMatch[2];
      if (!def.options[name]) {
        throw new GrammarError(ctx, at, name.length, `unknown option '${name}' for fx${didYouMean(name, optionNames)}`, `options for fx: ${optionNames.join(", ")}`);
      }
      if (value === "") {
        throw new GrammarError(ctx, at, t.length, `expected a value after '${name}='`, `e.g. ${name}=${def.options[name] === "px" ? "40px" : "600ms"}`);
      }
      if (opt[name] !== undefined) {
        throw new GrammarError(ctx, at, t.length, `'${name}' is given twice`);
      }
      const valueAt = at + name.length + 1;
      opt[name] = def.options[name] === "px" ? pxValue(ctx, value, valueAt) : emberDurationValue(ctx, value, valueAt);
      continue;
    }

    // Position, not membership, decides the preset: it's whatever comes
    // right after `fx`. This is why `bounce` (a preset) and `bounce` (an
    // easing modifier — see ember-easings.js) don't collide: `fx bounce`
    // is the preset, `fx shake bounce` is shake eased by bounce.
    if (w === 0) {
      if (presetNames.indexOf(t) === -1) {
        throw new GrammarError(ctx, at, t.length, `unknown preset '${t}'${didYouMean(t, presetNames)}`, `presets: ${presetNames.join(", ")}`);
      }
      preset = t;
      continue;
    }

    if (/^\d/.test(t)) {
      if (opt.duration !== undefined) {
        throw new GrammarError(ctx, at, t.length, "'duration' is given twice");
      }
      opt.duration = emberDurationValue(ctx, t, at);
      continue;
    }

    if (modifierNames.indexOf(t) !== -1) {
      if (mods.indexOf(t) !== -1) {
        throw new GrammarError(ctx, at, t.length, `'${t}' is given twice`);
      }
      mods.push(t);
      continue;
    }

    throw new GrammarError(ctx, at, t.length, `unknown flag '${t}' for fx${didYouMean(t, modifierNames)}`, `modifiers: ${modifierNames.join(", ")}`);
  }

  if (preset === null) {
    throw new GrammarError(ctx, restAt, Math.max(rest.length, 1), "fx needs a preset name", `presets: ${presetNames.join(", ")}`);
  }

  const params = {};
  if (opt.distance !== undefined) params.distance = opt.distance;
  if (opt.duration !== undefined) params.duration = opt.duration;
  const paramKeys = Object.keys(params);
  const hasParams = paramKeys.length > 0;
  // Unquoted keys (`{distance: 40, duration: 600}`), matching how a person
  // would hand-write the legacy `with { }` clause — not JSON.stringify's
  // quoted-key form, which is equally valid JS but not what ember's own
  // examples/README use, and not what a byte-for-byte legacy comparison
  // expects.
  const paramsText = `{${paramKeys.map((k) => `${k}: ${params[k]}`).join(", ")}}`;
  const runtimeName = def.presetMap[preset] || preset;
  const chain = [runtimeName].concat(mods).join(".");

  // Emit true legacy `fx` text when the id fits the legacy tokenizer (same
  // restriction as Quark's hyphenated-id case above), so the statement runs
  // through ember's own, completely unchanged parser and Ember.play(...)
  // call — proof by construction that ember "passes unchanged". A
  // hyphenated id falls back to the direct call, with the exact same
  // arguments Ember.play(elementId, presetName, modifiers, params) takes.
  if (LEGACY_ID_RE.test(id)) {
    return `fx ${id} ${chain}` + (hasParams ? ` with ${paramsText}` : "");
  }
  const args = [JSON.stringify(id), JSON.stringify(runtimeName), JSON.stringify(mods)];
  args.push(hasParams ? paramsText : "undefined");
  return `JS { Ember.play(${args.join(", ")}); }`;
}

// `<plugin>.<name> = <value>` — a whole-app setting, no `@id`. Only
// `quark.family` exists today (SETTINGS above).
function settingStatement(ctx, unit, text, textStart) {
  const m = /^([A-Za-z_][A-Za-z0-9_-]*)\.([A-Za-z_][A-Za-z0-9_-]*)\s*=\s*([\s\S]*)$/.exec(text);
  if (!m) return null;
  const key = `${m[1]}.${m[2]}`;
  const def = SETTINGS[key];
  if (!def) return null; // not a known setting — could be legacy `quark.family = family:soft` or unrelated text
  const raw = m[3].trim();
  const valueAt = textStart + text.length - m[3].length + (m[3].length - m[3].trimStart().length);
  if (raw === "") {
    throw new GrammarError(ctx, textStart, text.length, `expected a value after '${key} ='`, `e.g.  ${key} = ${def.values[0]}`);
  }
  const val = raw.replace(/^(["'])(.*)\1$/, "$2");
  if (def.values.indexOf(val) === -1) {
    throw new GrammarError(ctx, valueAt, raw.length, `unknown value '${val}' for ${key}${didYouMean(val, def.values)}`, `${key} is one of: ${def.values.join(", ")}`);
  }
  return def.compile(val);
}

// ---------------------------------------------------------------- campfire
//
// campfire has no `@id` (speakers and dialogue aren't tied to an element)
// and no dotted legacy form to reuse, so these three get their own parsing
// rather than going through elementRule()/directive(). Each one only claims
// text that is UNAMBIGUOUSLY v2: `speaker` is a brand-new leading keyword
// (legacy is `def SPEAKER …`, never bare `speaker`), `choice` claims only
// when a `{` follows the prompt (legacy closes with `end choice`, never a
// brace), and `say` claims only when it has a `wait=` clause (legacy's
// `wait 2000` has no `=`; `say id "line"` alone is already identical in
// both syntaxes, so there is nothing to rewrite). Anything not clearly ours
// returns null and falls through to campfire's own unchanged parser.

// speaker <id> name="<Display Name>" color=<color>
function campfireSpeaker(ctx, text, textStart) {
  const KW = "speaker";
  const rest = text.slice(KW.length);
  const restStart = textStart + KW.length;
  const words = splitWords(rest);
  if (words.length === 0) {
    throw new GrammarError(ctx, textStart, KW.length, "'speaker' needs an id", 'e.g. speaker aria name="Aria" color=#ffcc66');
  }
  const idWord = words[0];
  const id = idWord.text;
  const idAt = restStart + idWord.start;
  if (!LEGACY_ID_RE.test(id)) {
    throw new GrammarError(ctx, idAt, id.length, `'${id}' is not a valid speaker id`, "speaker ids are plain words, e.g. aria, narrator");
  }

  const opt = {};
  for (let w = 1; w < words.length; w++) {
    const word = words[w];
    const at = restStart + word.start;
    const t = word.text;
    const optMatch = /^(name|color)=([\s\S]*)$/.exec(t);
    if (!optMatch) {
      throw new GrammarError(ctx, at, t.length, `unexpected '${t}'`, 'speaker takes name="…" and color=…, e.g. speaker aria name="Aria" color=#ffcc66');
    }
    const name = optMatch[1];
    const value = optMatch[2];
    if (opt[name] !== undefined) {
      throw new GrammarError(ctx, at, t.length, `'${name}' is given twice`);
    }
    const valueAt = at + name.length + 1;
    if (name === "name") {
      if (!/^"[^"\n]*"$/.test(value)) {
        throw new GrammarError(ctx, valueAt, value.length, "name needs a quoted string", 'e.g. name="Aria"');
      }
      opt.name = value;
    } else {
      opt.color = colorValue(ctx, value, valueAt);
    }
  }
  if (opt.name === undefined || opt.color === undefined) {
    throw new GrammarError(ctx, textStart, text.length, "speaker needs both name= and color=", 'e.g. speaker aria name="Aria" color=#ffcc66');
  }
  return `JS { Campfire.defineSpeaker(${JSON.stringify(id)}, { name: ${opt.name}, color: ${JSON.stringify(opt.color)} }); }`;
}

// say <id> "<line>" [wait=<duration>]
function campfireSay(ctx, text, textStart) {
  const KW = "say";
  const rest = text.slice(KW.length);
  const restStart = textStart + KW.length;
  const words = splitWords(rest);
  if (words.length < 2) return null; // not enough to be either form — leave it
  const idWord = words[0];
  const lineWord = words[1];
  if (!/^"[^"\n]*"$/.test(lineWord.text)) return null; // not `say id "line" …` at all — not ours

  if (words.length === 2) return null; // identical in both syntaxes — no rewrite needed
  if (words.length > 3) return null; // not a shape v2 defines — leave it to campfire's own parser
  const tail = words[2];
  const optMatch = /^wait=([\s\S]*)$/.exec(tail.text);
  if (!optMatch) return null; // e.g. legacy's bare `wait 2000` — leave it

  const id = idWord.text;
  const idAt = restStart + idWord.start;
  if (!LEGACY_ID_RE.test(id)) {
    throw new GrammarError(ctx, idAt, id.length, `'${id}' is not a valid speaker id`, "speaker ids are plain words, e.g. aria");
  }
  const at = restStart + tail.start;
  const valueAt = at + "wait=".length;
  const wait = emberDurationValue(ctx, optMatch[1], valueAt);
  return `JS { Campfire.say(${JSON.stringify(id)}, ${lineWord.text}, { wait: ${wait} }); }`;
}

// choice <id> "<prompt>" { option "<label>" signal=<name> … }
function campfireChoice(ctx, text, textStart) {
  const head = /^choice\s+(\S+)\s+("(?:[^"\\\n]|\\.)*")/.exec(text);
  if (!head) return null; // not shaped like `choice id "prompt" …` — leave it
  const afterPrompt = text.slice(head[0].length).trimStart();
  if (!afterPrompt.startsWith("{")) return null; // legacy `… end choice` form — leave it

  const id = head[1];
  const promptLiteral = head[2];
  if (!LEGACY_ID_RE.test(id)) {
    const idAt = textStart + text.indexOf(id, "choice".length);
    throw new GrammarError(ctx, idAt, id.length, `'${id}' is not a valid speaker id`, "speaker ids are plain words, e.g. aria");
  }

  const braceStart = text.indexOf("{", head[0].length);
  const close = text.lastIndexOf("}");
  if (close === -1 || close < braceStart) {
    throw new GrammarError(ctx, textStart, text.length, "'choice' block is missing its closing '}'", 'e.g. choice aria "…" { option "…" signal=name }');
  }
  const body = text.slice(braceStart + 1, close);
  const bodyStart = textStart + braceStart + 1;

  const options = [];
  let lineOffset = 0;
  for (const rawLine of body.split("\n")) {
    const line = rawLine.trim();
    const indent = rawLine.length - rawLine.trimStart().length;
    const lineAt = bodyStart + lineOffset + indent;
    lineOffset += rawLine.length + 1;
    if (line === "" || line.startsWith("//")) continue;
    const om = /^option\s+("(?:[^"\\\n]|\\.)*")\s+signal=([A-Za-z_][A-Za-z0-9_]*)\s*$/.exec(line);
    if (!om) {
      throw new GrammarError(ctx, lineAt, line.length, `expected 'option "<label>" signal=<name>'`, 'e.g. option "Sure." signal=stayFriendly');
    }
    options.push({ label: om[1], signal: om[2] });
  }
  if (options.length === 0) {
    throw new GrammarError(ctx, textStart, text.length, "'choice' needs at least one 'option'");
  }
  const optionsArg = options.map((o) => `{ label: ${o.label}, signal: ${JSON.stringify(o.signal)} }`).join(", ");
  return `JS { Campfire.choice(${JSON.stringify(id)}, ${promptLiteral}, [${optionsArg}]); }`;
}

// Dispatches to whichever of the three claims this statement, or null.
function campfireStatement(ctx, unit, text, textStart) {
  if (/^speaker(?=\s)/.test(text)) return campfireSpeaker(ctx, text, textStart);
  if (/^say(?=\s)/.test(text)) return campfireSay(ctx, text, textStart);
  if (/^choice(?=\s)/.test(text)) return campfireChoice(ctx, text, textStart);
  return null;
}

// ---------------------------------------------------------------- legacy rejection
//
// See docs/design/LANGUAGE-PLAN.md's "KNOWN ARCHITECTURAL DEBT" section.
// Everything above only ever recognizes and rewrites v2 shapes; anything it
// doesn't recognize used to be passed through untouched and silently
// compiled via the original, still-intact legacy parsers underneath this
// plugin. This function closes that gap for the specific shapes the plan
// names (`@requires`, `@useLib`, dotted-preset assignment, `def PROP`,
// `add new action`, legacy `fx`, `def SPEAKER`) by turning each one into a
// build error, WITHOUT deleting the legacy parsers themselves — a real
// .cdrca file typed by a person now gets a compile error; the legacy
// parsers are still there because a v2 rewrite's OUTPUT still runs through
// them (see the file header).
//
// Why this is safe to key on raw text, unlike everything else being a
// rewrite: desugar() only ever scans UNITS OF THE ORIGINAL SOURCE
// (`scanUnits(src)`, computed once, before any rewriting runs) — never its
// own rewritten output. A v2 statement's compiled text (e.g.
// `@nav navbar.glass = accent` or `@requires quark`) is written to `out`,
// not re-scanned, so a human typing that exact legacy text and a rewrite
// producing it are never confused for each other even though they can look
// byte-identical.
//
// `allowLegacy` is an internal escape hatch (`options.__internalAllowLegacySyntax`
// on the top-level `transpile()` call) for this plugin's own test suite,
// which proves "v2 compiles to exactly what legacy produces" by compiling
// real legacy text on one side of the comparison — see equivalence.test.js,
// grammar.test.js and animations-v2.test.js. It is not reachable from any
// .cdrca source file, so it does not reopen the gap for a real project.
// `@IMPORT` is deliberately NOT included below: docs/design/LANGUAGE-PLAN.md
// keeps it working, unchanged, on purpose (see grammar.test.js's own
// "legacy: a header @IMPORT chain still loses everything..." tests) — it
// was never part of this cleanup.
//
// Deliberately NOT covered here (tracked as follow-up, not attempted in
// this pass): `R.store(...)`/`R.query(...)` called directly inside a
// hand-written `js { }` block. That block's body is intentionally opaque
// raw JavaScript to this plugin; scanning inside it for specific call
// shapes would mean parsing arbitrary JS by regex, a different and much
// riskier kind of guess than any of the shapes below (which are all
// unambiguous, fixed leading keywords).
function legacyOnlyError(ctx, at, len, what, v2Spelling) {
  throw new GrammarError(
    ctx,
    at,
    len,
    `'${what}' is not v2 syntax`,
    `write this in v2 instead: ${v2Spelling}`
  );
}

function rejectLegacySyntax(ctx, text, textStart) {
  // @requires / @useLib / @AddImport written directly. v2 spells these
  // `require a, b` / `load plugin.lib` / `import "file.cdrca"` — this
  // plugin itself is the only thing that ever emits the literal text below.
  let m = /^@(AddImport|requires|useLib)\b/.exec(text);
  if (m) {
    const kw = m[1];
    const v2 = kw === "AddImport" ? 'import "file.cdrca"' : kw === "requires" ? "require pluginA, pluginB" : "load plugin.library";
    legacyOnlyError(ctx, textStart, ("@" + kw).length, "@" + kw, v2);
  }

  // A Quark/animations dotted preset.modifier[.modifier…] = value
  // assignment — the legacy shape v2's own flags-then-`accent=`/`family=`
  // rewrite targets. `bind.<path> = …` (reactive-state wiring) is excluded
  // on purpose: "bind" is never a component name, only a wiring word.
  m = /^@([A-Za-z_][A-Za-z0-9_-]*)\s+([A-Za-z_][A-Za-z0-9_-]*(?:\.[A-Za-z_][A-Za-z0-9_-]*)+)\s*=\s*[\s\S]+$/.exec(text);
  if (m) {
    const head = m[2].split(".")[0];
    const isComponent = Object.keys(ctx.vocab).some((p) => ctx.vocab[p].capabilities && ctx.vocab[p].capabilities[head]);
    if (isComponent) {
      legacyOnlyError(ctx, textStart, text.length, `@${m[1]} ${m[2]} = …`, `@${m[1]} ${head} <flags…> [accent=#hex]`);
    }
  }

  // def PROP / def ACTION / def SPEAKER — v2 spells these `object` /
  // `action` / bare `speaker`.
  m = /^def\s+(PROP|ACTION|SPEAKER)\b/.exec(text);
  if (m) {
    const v2 = m[1] === "PROP" ? "object <name> = Ctor(args)" : m[1] === "ACTION" ? "action <name> [stay=…ms] [lerp=…ms] { … }" : 'speaker <id> name="…" color=#hex';
    legacyOnlyError(ctx, textStart, text.length, `def ${m[1]}`, v2);
  }

  // use <name>(...) [as alias] — v2 spells the whole prop declaration as
  // `object <name> = Ctor(...)`.
  if (/^use\s+[A-Za-z_][\w.]*\s*\(/.test(text)) {
    legacyOnlyError(ctx, textStart, text.length, "use", "object <name> = Ctor(args)");
  }

  // add new action ... — v2 spells this `action <name> { … }`.
  if (/^add\s+new\s+action\b/.test(text)) {
    legacyOnlyError(ctx, textStart, text.length, "add new action", "action <name> [stay=…ms] [lerp=…ms] { … }");
  }

  // bare `fx <id> <chain>` (no leading @) — v2 always writes fx as an
  // element rule: `@id fx preset ...`.
  m = /^fx\s+([A-Za-z_][A-Za-z0-9_-]*)\s/.exec(text);
  if (m) {
    legacyOnlyError(ctx, textStart, text.length, "fx", `@${m[1]} fx <preset> [modifiers…] [distance=…px] [duration=…ms]`);
  }

  // choice <id> "<prompt>" … end choice (no opening brace) — v2 always
  // closes a choice block with `{ … }`.
  m = /^choice\s+(\S+)\s+"(?:[^"\\\n]|\\.)*"/.exec(text);
  if (m && !text.slice(m[0].length).trimStart().startsWith("{")) {
    legacyOnlyError(ctx, textStart, text.length, "choice … end choice", 'choice <id> "<prompt>" { option "<label>" signal=<name> … }');
  }
}

// ---------------------------------------------------------------- registry
//
// Every rule the grammar applies is an entry in an ordered registry, not a
// call hardcoded into desugar(). Three lists, each run in order, first
// non-null result wins:
//
//   element   — statements starting with "@"        (`@id capability ...`)
//   statement — every other statement                (`require`, `object`, ...)
//   guard     — run only when nothing above claimed the statement; a guard
//               either throws (a helpful error) or returns, never rewrites
//
// Each entry is { name, owner, fn }. `owner` is "base" for everything in this
// file. A plugin author working in their copy of the grammar adds entries
// with a different owner; the packager (step 2) reads the registry, not the
// source text, to tell "added" from "modified": a base entry that is missing,
// renamed, reordered or replaced is a change to shared behaviour and is
// rejected, while entries with a new owner are the plugin's own additions.
//
// Order matters and is part of the contract: the base order below is
// exactly what desugar() used to hardcode, and nothing may be inserted
// before a base entry — additions run after all base entries of their list.
const BASE_OWNER = "base";
const LISTS = ["element", "statement", "guard"];

function createRegistry() {
  const lists = { element: [], statement: [], guard: [] };
  const names = new Set();
  // Copy-on-write view of the vocabulary: base entries are shared, never
  // mutated; a declaration replaces the affected plugin entry with a copy.
  const vocab = Object.assign({}, VOCABULARY);
  const declarations = [];
  return {
    lists,
    vocab,
    // Declare vocabulary for a plugin. Additive only:
    //  - a NEW plugin name may declare any `capabilities`;
    //  - an EXISTING plugin may only gain new capability names;
    //  - a capability name may not already exist in ANY plugin (a bare
    //    `@id name` must never become ambiguous because a library was added).
    // Declared capabilities are tagged `__owner`, which tells the base
    // element rule to leave them to the declaring plugin's own rule.
    declare(plugin, decl, owner) {
      if (!owner || owner === BASE_OWNER) throw new Error("grammar registry: a declaration needs a non-base owner");
      if (!/^[a-z][a-z0-9-]*$/.test(String(plugin))) throw new Error(`grammar registry: '${plugin}' is not a valid plugin name (lowercase letters, digits, hyphens)`);
      if (!decl || typeof decl !== "object" || !decl.capabilities || typeof decl.capabilities !== "object") {
        throw new Error(`grammar registry: declaration for '${plugin}' needs a 'capabilities' object`);
      }
      const existing = vocab[plugin];
      const extraKeys = Object.keys(decl).filter((k) => k !== "capabilities");
      if (existing && extraKeys.length) {
        throw new Error(`grammar registry: '${plugin}' already exists — a declaration may only add capabilities to it, not '${extraKeys.join("', '")}'`);
      }
      const capNames = Object.keys(decl.capabilities);
      if (!capNames.length) throw new Error(`grammar registry: declaration for '${plugin}' declares no capabilities`);
      for (const cap of capNames) {
        if (!/^[A-Za-z_][A-Za-z0-9_-]*$/.test(cap)) throw new Error(`grammar registry: '${cap}' is not a valid capability name`);
        for (const p of Object.keys(vocab)) {
          if (vocab[p].capabilities && vocab[p].capabilities[cap]) {
            throw new Error(`grammar registry: capability '${cap}' already exists in '${p}' — pick another name`);
          }
        }
        const def = decl.capabilities[cap];
        if (!def || typeof def !== "object" || Array.isArray(def)) throw new Error(`grammar registry: capability '${cap}' must be an object`);
        for (const k of ["variants", "modifiers"]) {
          if (def[k] !== undefined && !(Array.isArray(def[k]) && def[k].every((x) => typeof x === "string"))) {
            throw new Error(`grammar registry: '${cap}.${k}' must be an array of strings`);
          }
        }
      }
      const caps = Object.assign({}, existing ? existing.capabilities : {});
      for (const cap of capNames) caps[cap] = Object.assign({ variants: [], modifiers: [] }, decl.capabilities[cap], { __owner: owner });
      vocab[plugin] = existing ? Object.assign({}, existing, { capabilities: caps }) : Object.assign({}, decl, { capabilities: caps });
      declarations.push({ plugin, capabilities: capNames.slice(), owner });
    },
    register(list, name, fn, owner) {
      if (LISTS.indexOf(list) === -1) throw new Error(`grammar registry: unknown list '${list}' (expected ${LISTS.join(", ")})`);
      if (typeof fn !== "function") throw new Error(`grammar registry: '${name}' must be a function`);
      const own = owner || BASE_OWNER;
      const key = list + ":" + name;
      if (names.has(key)) throw new Error(`grammar registry: '${name}' is already registered in the ${list} list`);
      names.add(key);
      lists[list].push({ name, owner: own, fn });
    },
    // A plain, serialisable description — what the packager diffs against.
    describe() {
      const out = {};
      for (const l of LISTS) out[l] = lists[l].map((e) => ({ name: e.name, owner: e.owner }));
      out.declarations = declarations.map((d) => ({ plugin: d.plugin, capabilities: d.capabilities.slice(), owner: d.owner }));
      return out;
    },
  };
}

function runList(registry, list, ctx, unit, text, textStart) {
  const entries = registry.lists[list];
  for (let i = 0; i < entries.length; i++) {
    const r = entries[i].fn(ctx, unit, text, textStart);
    if (r !== null && r !== undefined) return r;
  }
  return null;
}

// The base grammar. Order is the pre-registry hardcoded order — keep it.
function createBaseRegistry() {
  const reg = createRegistry();
  reg.register("element", "elementRule", elementRule);
  reg.register("statement", "directive", directive);
  reg.register("statement", "animationsDeclaration", animationsDeclaration);
  reg.register("statement", "settingStatement", settingStatement);
  reg.register("statement", "campfireStatement", campfireStatement);
  reg.register("guard", "rejectLegacySyntax", function (ctx, unit, text, textStart) {
    rejectLegacySyntax(ctx, text, textStart);
    return null;
  });
  return reg;
}

// ---------------------------------------------------------------- plugin API
//
// What a plugin author's code can see. In their workspace copy of this file
// they can reach anything in file scope, but the packaged plugin is loaded by
// applyPackage() below with ONLY the names in PLUGIN_API_NAMES in scope, so
// the packager refuses code that leans on anything else (see packager.js).

// Split `@id capability rest`, positions relative to the whole file. Returns
// null if the text isn't shaped like an element statement.
function splitElement(text, textStart) {
  const m = /^@([A-Za-z_][A-Za-z0-9_-]*)\s+(\S+)(?:\s+([\s\S]*))?$/.exec(text);
  if (!m) return null;
  const capOffset = text.indexOf(m[2], m[1].length + 1);
  const afterCap = capOffset + m[2].length;
  const rest = (m[3] || "").trim();
  const restOffset = rest === "" ? afterCap : afterCap + (text.slice(afterCap).length - text.slice(afterCap).trimStart().length);
  return { id: m[1], idAt: textStart + 1, cap: m[2], capAt: textStart + capOffset, rest, restAt: textStart + restOffset };
}

// A plugin's only way to add to the grammar. The owner is fixed when the API
// is created, so a plugin can't register or declare as anyone else.
function createPluginApi(registry, owner) {
  return Object.freeze({
    register(list, name, fn) { registry.register(list, name, fn, owner); },
    declare(plugin, decl) { registry.declare(plugin, decl, owner); },
  });
}

const PLUGIN_API_NAMES = ["GrammarError", "splitWords", "splitElement", "suggest", "didYouMean", "distance"];

// Apply a packaged plugin ({ format, owner, source }) to a registry. The source
// runs with only `PLUGIN` and the PLUGIN_API_NAMES helpers in scope.
function applyPackage(registry, pkg) {
  if (!pkg || pkg.format !== 1 || typeof pkg.source !== "string" || !pkg.owner) throw new Error("grammar: not a valid plugin package");
  const helpers = { GrammarError, splitWords, splitElement, suggest, didYouMean, distance };
  const fn = new Function("PLUGIN", ...PLUGIN_API_NAMES, '"use strict";\n' + pkg.source);
  fn(createPluginApi(registry, pkg.owner), ...PLUGIN_API_NAMES.map((n) => helpers[n]));
}

const DEFAULT_REGISTRY = createBaseRegistry();

// What a plugin author's workspace calls (PLUGIN.register / PLUGIN.declare).
// The owner here is a placeholder — the packager stamps the real one.
const PLUGIN = createPluginApi(DEFAULT_REGISTRY, "workspace");

// ---------------------------------------------------------------- driver

// Rewrite v2 statements into legacy ones. Returns the SAME string object's
// value untouched when there is nothing to rewrite.
function desugar(src, currentFile, allowLegacy, registry) {
  const reg = registry || DEFAULT_REGISTRY;
  const lineStarts = [0];
  for (let i = 0; i < src.length; i++) if (src.charCodeAt(i) === 10) lineStarts.push(i + 1);
  const ctx = { src, lineStarts, currentFile, vocab: reg.vocab };

  const units = scanUnits(src);
  let out = "";
  let cursor = 0;
  let changed = false;

  for (const unit of units) {
    if (unit.marker) continue;
    const codeEnd = unit.commentAt === -1 ? unit.end : unit.commentAt;
    const raw = src.slice(unit.start, codeEnd);
    const text = raw.trim();
    if (text === "") continue;
    const textStart = unit.start + (raw.length - raw.trimStart().length);

    const rewritten = runList(reg, text.charAt(0) === "@" ? "element" : "statement", ctx, unit, text, textStart);
    if (rewritten === null) {
      if (!allowLegacy) runList(reg, "guard", ctx, unit, text, textStart);
      continue;
    }

    // Keep line numbers stable for everything downstream: a statement that
    // spanned several lines is replaced by one line plus blank lines.
    // (A rewrite that already carries the original newlines — a `js { }`
    // block — needs no padding; counting them twice shifted every later line.)
    const lost = text.split("\n").length - rewritten.split("\n").length;
    const indent = src.slice(unit.start, textStart);
    const tail = unit.commentAt === -1 ? "" : " " + src.slice(unit.commentAt, unit.end);
    out += src.slice(cursor, unit.start) + indent + rewritten + "\n".repeat(Math.max(0, lost)) + tail;
    cursor = unit.end;
    changed = true;
    // If the statement's tail comment was re-emitted, `cursor = unit.end`
    // already skips past it in the source.
  }
  if (!changed) return src;
  return out + src.slice(cursor);
}

module.exports = function (pluginAPI) {
  pluginAPI.register(100, "before", "parse", function (source, options) {
    if (typeof source !== "string") return undefined;
    return desugar(source, options && options.currentFile, !!(options && options.__internalAllowLegacySyntax));
  });
};

module.exports.__internals = {
  desugar,
  resolveImport,
  scanUnits,
  splitWords,
  suggest,
  distance,
  VOCABULARY,
  SETTINGS,
  RESERVED_AT,
  GrammarError,
  animationsCapabilityRule,
  animationsDeclaration,
  sceneColorValue,
  PROP_PATH_PREFIX,
  emberFxRule,
  settingStatement,
  campfireStatement,
  campfireSpeaker,
  campfireSay,
  campfireChoice,
  pxValue,
  emberDurationValue,
  rejectLegacySyntax,
  createRegistry,
  createBaseRegistry,
  createPluginApi,
  applyPackage,
  splitElement,
  PLUGIN_API_NAMES,
  DEFAULT_REGISTRY,
  BASE_OWNER,
};
